[project]
name = "Gemini-Image-Tool"
version = "0.3.0"
description = "A multimodal image processing tool powered by Google GenAI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet[all]>=0.80.4",
    "google-genai>=1.60.0",
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "appdirs>=1.4.3",
    "openai>=2.16.0",
]
authors = [
    { name = "joycai", email = "joycai@joycai.cn" }
]

[dependency-groups]
dev = [
    "pylint>=4.0.4",
]

[tool.flet]
product = "Gemini-Image-Tool"
company = "Joycai"
copyright = "Copyright (C) 2025 by Joycai"
app.path = "src"
app.module = "main"

[tool.flet.app.boot_screen]
show = false
message = "Preparing the app for its first launch…"

[tool.flet.app.startup_screen]
show = false
message = "Starting up the app…"
